config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index]

  resources :artists do
    resources :songs
  end
  resources :mobile
  resources :favorites

  resources :session, except: [:destroy]
  resources :comments

  delete '/session/logout' => 'session#destroy'
  get '/songs/drop_song' => 'songs#drop_song'
  post '/songs/available' => 'songs#available_songs'

  resources :requests
  get '/nearby/requests' => 'requests#near'
  get '/near/requests/:params' => 'requests#near_songs'
  get '/songs/heat_map/:id' => 'songs#heat_map'

  root 'landings#index'
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController


  def index
    if logged_in?
      redirect_to current_user
    else
      render 'index'
    end
  end

end

app/views/landings/index.html.erb
<div id="home-jumbo" class=" text-center">
  <ul class = "cb-slideshow">
    <li><span>Image 01</span></li>
    <li><span>Image 02</span></li>
    <li><span>Image 03</span></li>
    <li><span>Image 04</span></li>
    <li><span>Image 05</span></li>
    <li><span>Image 06</span></li>
  </ul>
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <h1 class="logo">EarShot</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <section id="signin-register-form-wrapper">
          <%=render '/shared/flash' %>
          <%= link_to "Sign In", new_session_path,  class: "black-button sign-in-bttn  btn-lg" %>
          <%= link_to "Register", new_user_path,  class: "black-button register-bttn  btn-lg" %>
          </section>
          <br>
          <div class="form-holder form-container center-block"style="height:0;"></div>
        </div>
      </div>
    </div>
  </div>
</div>