config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index]

  resources :artists do
    resources :songs
  end
  resources :mobile
  resources :favorites

  resources :session, except: [:destroy]
  resources :comments

  delete '/session/logout' => 'session#destroy'
  get '/songs/drop_song' => 'songs#drop_song'
  post '/songs/available' => 'songs#available_songs'

  resources :requests
  get '/nearby/requests' => 'requests#near'
  get '/near/requests/:params' => 'requests#near_songs'
  get '/songs/heat_map/:id' => 'songs#heat_map'

  root 'landings#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_secure_password

  has_many :listens, dependent: :destroy
  has_many :artists, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :f_name, :l_name, :username, :email, presence: true
  validates :username, :email, uniqueness: true
  # validates :password, length: {minimum: 8}

  def user_is_artist?
    self.artists.count > 0
  end

  def available_songs(long, lat, all_songs)
    all_songs.select do |song|
      puts "song radius: #{song.locations.first.radius}"
      puts "song.name: #{song.in_range?(lat, long)}"
      song.in_range?(lat, long)
    end
  end

  def distance_between(user_lat, user_long, song_lat, song_long)
    earth_radius = 6378.137
  end

  def favorite_active_songs
    active_songs = []
    self.favorites.each do |favorite|
      if favorite.song.locations.first.active?
        active_songs << favorite
      end
    end
    active_songs
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # skip_before_action :redirect_visitors, only: [ :create, :new, :edit, :destroy, :update]
  # skip_before_action :verify_authenticity_token
  # before_action :authenticate!, only: [:show, :edit, :update, :destroy]
  def new
    @user = User.new
    if request.xhr?
      render '/users/_new', layout: false
    else
      render 'new'
    end
  end

  def show
    @songs = Song.all
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      if request.xhr?
        render :json => {:user_id => @user.id, :status => true}
      else
        redirect_to "/users/#{@user.id}"
      end
    else
      if request.xhr?
       render :json => {:error => "Invalid user credentials"}, :status => 422
      else
        @errors = @user.errors.full_messages
        render 'new'
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if request.xhr?
      render '_edit_user', layout: false, locals: {user: @user}
    else
      render 'edit'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'Your profile was successfully updated.'
    else
      render 'edit'
    end
  end



  def destroy
    @user.destroy
    session.delete(:user_id)
    redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:f_name, :l_name, :username, :email, :password, :password_confirmation,:profile_picture)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def redirect_visitors
    if visitor?
      redirect_to '/'
    end
  end

  def visitor?
    session[:user_id] == nil
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    puts "logged in? #{session[:user_id] != nil}"
    session[:user_id] != nil
  end

  def current_user
    if logged_in?
      @current_user = User.find(session[:user_id])
    end
  end

  def log_out
    session.delete(:user_id)
    current_user = nil
  end




end

app/views/users/_edit_user.html.erb
<%= form_for(user) do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :f_name %><br>

  <%= f.label :last_name %>
  <%= f.text_field :l_name %><br>

  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.submit "Update" %>

<% end %>

app/views/users/_greeting.html.erb
<div class="col-md-12">
  <h1 class="text-center">Welcome <%=@user.username%></h1>
</div>

app/views/users/_new.html.erb
<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4 form-wrapper text-left">
            <%=render '/shared/errors' %>
          <%= form_for @user, :html => {:role => "form", :class => "registration-form"} do |f| %>

          <div class="form-group">
            <%= f.text_field :f_name, class: "form-control", placeholder: "First Name" %>
          </div>

          <div class="form-group">
            <%= f.text_field :l_name, class: "form-control", placeholder: "Last Name" %>
          </div>

          <div class="form-group">
            <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
          </div>

          <div class="form-group">
            <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
          </div>
          <div class="input-group">
          <%= f.submit "Register", class: "btn btn-default" %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_parallax.html.erb
<img class="user-image center-block img-rounded" src="https://unsplash.imgix.net/photo-1421986527537-888d998adb74?w=1024&amp;q=50&amp;fm=jpg&amp;s=e633562a1da53293c4dc391fd41ce41d"
width="304" height="236">

app/views/users/_show.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#">Add Artist</a></li>
  <% @user.artists.each do |artist|%>
    <li><%= link_to artist.name, artist_path(artist)%></li>
  <% end %>
</ul>
<div class="tab-content">
  <% @user.artists.each do |artist|%>
    <% @artist = artist%>
    <%= render 'artists/show' %>
  <% end %>
</div>

app/views/users/_user_artists.html.erb
<div class="user-artist-module col-sm-12 col-md-4">
  <table class="table">
    <tr>
      <th><h2 class="text-center">Artist Page</h2></th>
      <th><button type="button" class="btn btn-success add-artist-btn">
        <%= link_to "+ Artist", new_artist_path, class: "nav-link " %>
      </button></th>
    </tr>
    <tr>
      <th>Artist Page</th>
    </tr>
    <% @user.artists.each do |artist|%>
    <tr><td><%= link_to artist.name, artist_path %></td></tr>
    <% end %>
  </table>
</div>

app/views/users/_user_content.html.erb
<%= render 'media/available_songs'%>

app/views/users/_user_info.html.erb
<section class="user-info-wrapper col-sm-12">

  <h1>Welcome <%=@user.username%></h1>
  <table class="table">
    <tr><td>User info: <%= link_to "Edit", edit_user_path, class: "edit-user-btn" %></td></tr>
    <tr><td><%= @user.f_name%> <%= @user.l_name%></td></tr>
     <tr><td><%= @user.email%></td></tr>
  </table>
</section>

app/views/users/edit.html.erb
<div class="modal-body">

  <%= form_for @user, :html => {:role => "form", :class => "registration-form"} do |f| %>

  <div class="form-group">
    <%= f.label "First Name" %>
    <%= f.text_field :f_name, class: "form-control", placeholder: "First Name" %>
  </div>

  <div class="form-group">
    <%= f.label "Last Name" %>
    <%= f.text_field :l_name, class: "form-control", placeholder: "Last Name" %>
  </div>

  <div class="form-group">
    <%= f.label "Username" %>
    <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
  </div>

  <div class="form-group">
    <%= f.label "Email" %>
    <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>

  <div class="form-group">
    <%= f.label "Profile Picture" %>
    <%= f.text_field :profile_picture, class: "form-control" %>
  </div>

  <div class="input-group">
  <%= f.submit "Edit", class: "btn btn-default" %>
  </div>
  <% end %>

</div>

app/views/users/new.html.erb
<div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4 text-left">
          <%= form_for @user, :html => {:role => "form", :class => "registration-form"} do |f| %>

          <div class="form-group">
            <%= f.text_field :f_name, class: "form-control", placeholder: "First Name" %>
          </div>

          <div class="form-group">
            <%= f.text_field :l_name, class: "form-control", placeholder: "Last Name" %>
          </div>

          <div class="form-group">
            <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
          </div>

          <div class="form-group">
            <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
          </div>

          <div class="form-group">
            <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
          </div>
          <div class="input-group">
          <%= f.submit "Register", class: "btn btn-default" %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<article class="greeting container">
  <section class="row">
    <div class="col-md-12">
      <h1 class="text-center">Welcome <%=@user.username%>
    </div>
  </section>
</article>

<section class="module parallax parallax-1">
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="span4"></div>
        <div class="span4">
          <% if @user.profile_picture %>
          <img class="center-block img-rounded" src="<%= @user.profile_picture %>"
          width="304" height="236">
          <% else %>
          <img class="center-block img-rounded" src="https://www.drupal.org/files/profile_default.png"
          width="304" height="236">
          <% end %>
        </div>
        <div class="text-center">
          <% if current_user.id == @user.id%>
          <!-- Button trigger modal -->
          <button class="btn black-button btn-lg" data-toggle="modal" data-target="#myModalHorizontal">
          Edit Profile
          </button>

          <!-- Modal -->
          <div class="modal fade" id="myModalHorizontal" tabindex="-1" role="dialog"
           aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
              <div class="modal-content">
                  <!-- Modal Header -->
                  <div class="modal-header">
                      <button type="button" class="close"
                         data-dismiss="modal">
                             <span aria-hidden="true">&times;</span>
                             <span class="sr-only">Close</span>
                      </button>
                      <h4 class="modal-title" id="myModalLabel">
                          Edit Profile
                      </h4>
                  </div>

                  <!-- Modal Body -->
                  <div class="modal-body">
                      <%= render template: '/users/edit'%>
                  </div>

                  <!-- Modal Footer -->
                  <div class="modal-footer">
                      <button type="button" class="btn btn-default"
                              data-dismiss="modal">
                                  Close
                      </button>
                  </div>
              </div>
          </div>
          </div>
          <%end%>
        </div>
        <div class="span4"></div>
      </div>
    </div>
  </div>
</section>

<main class="container">
  <article class="row user-info-wrapper">

    <section class="user-media-wrapper col-ex-12 col-sm-6">
      <%= render 'users/user_content'%>
    </section>

    <section class="user-map-wrapper col-ex-12 col-sm-6">
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDjMxrwns8Hvjk3ax8QTAYxei7Ilpen3AM&libraries=drawing,places,visualization&callback=initUserMap" async defer></script>
       <div id="user-map"></div>
    </section>

  </article>
</main>

          <div class="section">
            <div class="container">
              <div class="row">
                <div class="col-md-12">
                  <% if @user.artists.count > 0 %>
                  <h1 class="text-center"><%= link_to "Manage Artist Profile", artist_path(current_user.artists.first.id), class: "nav-link ", id: "artist_show_link" %></h1>
                  <%else%>
                  <h1 class=" text-center"><%= link_to "Create Artist Profile", new_artist_path%></h1>
                  <%end%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>