config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index]

  resources :artists do
    resources :songs
  end
  resources :mobile
  resources :favorites

  resources :session, except: [:destroy]
  resources :comments

  delete '/session/logout' => 'session#destroy'
  get '/songs/drop_song' => 'songs#drop_song'
  post '/songs/available' => 'songs#available_songs'

  resources :requests
  get '/nearby/requests' => 'requests#near'
  get '/near/requests/:params' => 'requests#near_songs'
  get '/songs/heat_map/:id' => 'songs#heat_map'

  root 'landings#index'
end

app/models/song.rb
class Song < ActiveRecord::Base

  belongs_to :artist
  has_many :locations, dependent: :destroy
  has_many :listens
  has_many :favorites
  has_many :comments

  # mount_uploader :attachment, AttachmentUploader

  # has_attached_file :artwork
  # validates_attachment_content_type :artwork, :content_type => ["image/html", "image/jpg", "image/png", "image/jpeg"]

  accepts_nested_attributes_for :locations

  validates :name, :attachment, presence: true
  # def song_location
  #   self.locations.first.lat.to_s + ", " + self.locations.first.long.to_s
  # end

  # def address
  #   self.
  # end

  # def address_location
  #   self.address_components.address[2]["long_name"]
  # end

  # def address_city
  #   self.address_components.address[3]["short_name"]
  # end


  def neighborhood
    self.locations.first.neighborhood
  end

  def city
    self.locations.first.city
  end

  def expire
    self.locations.first.expiration ||= nil
  end

  def in_range?(user_lat, user_long)
    song_lat = self.locations.first.lat.to_f
    song_long = self.locations.first.long.to_f
    distance_between = self.measure(user_lat.to_f, user_long.to_f, song_lat, song_long)
     song_radius = self.locations.first.radius
     puts "radius: #{song_radius} distance: #{distance_between }"
    distance_between < song_radius
  end

   def measure(lat1, lon1, lat2, lon2)
      radius = 6378.137 # Radius of earth in KM
      dLat = (lat2 - lat1) * Math::PI / 180;
      dLon = (lon2 - lon1) * Math::PI / 180;
      a = Math::sin(dLat/2) * Math::sin(dLat/2) +
      Math::cos(lat1 * Math::PI / 180) * Math::cos(lat2 * Math::PI / 180) *
      Math::sin(dLon/2) * Math::sin(dLon/2);
      c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a));
      d = radius * c;
      return d * 1000; # meters

  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # require 'aws/s3'


  def new
    @artist = Artist.find(params[:artist_id])
    @song = Song.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    song_data = params[:song][:attachment]
    art_data = params[:song][:artwork]
    if song_data != nil && art_data != nil
      song_obj = S3_BUCKET.objects.create(song_data.original_filename, song_data.tempfile)
      art_obj = S3_BUCKET.objects.create(art_data.original_filename, art_data.tempfile)
      root = "http://ear-shot-mp3.s3.amazonaws.com/"
      song_url = root + song_data.original_filename
      art_url = root + art_data.original_filename
      @song = @artist.songs.new(name: params[:song][:name], attachment: song_url, artwork: art_url)
      @location = @song.locations.new(expiration: params[:song][:location][:expiration], lat: params[:song][:location][:lat], long: params[:song][:location][:long], radius: params[:song][:location][:radius] )
      if @song.save && @location.save
        redirect_to @artist
      else
        @errors = ["Make sure you've selected a location","Make sure you've entered a name","Make sure you're file is an mp3"]
        render "/artists/show"
      end
    else
      @errors = ["Something went wrong, try again!"]
      # render "/artists/show"
      redirect_to @artist
    end
  end


  def show
    @song = Song.find(params[:id])
    if request.xhr?
      render '_show', layout: false, locals: {song: @song}
    else
      render 'show'
    end
  end
  def update
    @song = Song.find(params[:id])
  end

  def drop_song
      puts ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
      puts "inside ajx"
      render'/artists/_artist_drop_song', layout: false
  end


  def available_songs
    longitude = params[:longitude]
    latitude = params[:latitude]
    # longitude = "1000000000000"
    # latitude = "1000000000000000"
    all_songs = Song.all
    puts "all songs: #{all_songs.count}"
    @songs = current_user.available_songs(longitude, latitude, all_songs)
    puts "available songs: #{@songs.count}"
    render partial: 'songs/all_songs', layout: false
  end

  def heat_map
    if request.xhr?
      @song = Song.find(params[:id])
      render :json => @song.listens, :only => [:long, :lat]
    end

  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to @song.artist
  end




  private
    def song_params
      params.require(:song).permit(:name, :artist_id, :attachment, :artwork, :location => [:expiration, :lat, :long, :radius])
    end
end

app/helpers/songs_helper.rb
module SongsHelper
  def remote_upload(song)
    S3_BUCKET.objects.create(song, @file_data.tempfile)
  end

  def last_5(user_id)
    Listen.where(user_id: user_id).last(10)
  end
end

app/views/songs/_all_songs.html.erb
<table class="table">
  <% @songs.each do |song| %>
  <tr>
    <td class="media-column">
      <audio id="song<%= song.id %>" class="media-songs" src="<%= song.attachment %>"></audio>
          <button class="media-play-btn btn btn-default" song="<%= song.id%>"><span class="glyphicon glyphicon-play" aria-hidden="true"></span>
          </button>

      </button>
    </td>
    <td class="media-column"><img class="artwork-thumbnail" src="<%= song.artwork %>"></td>
    <td class="media-column"><%= song.name %></td>
    <td class="media-column"><%= song.artist.name %></td>

  </tr>

  <% end %>
</table>

app/views/songs/_new.html.erb
<%= form_for :song, url: artist_songs_path(@artist), :html => {:role => "form"} do |f| %>

  <% if @location_errors %>
  <ul>
    <% @location_errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>


  <div class="form-group">
    <%= f.label "Song Name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.label "Art Work" %>
  <div class="input-group">
    <span class="input-group-btn">
      <span class="btn btn-small black-button btn-inverse" onclick="$(this).parent().find('input[type=file]').click();">Browse</span>
      <%= f.file_field :artwork, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
    </span>
    <span class="form-control"></span>
  </div>
  <%= f.label "Song File" %>
  <div class="input-group">
    <span class="input-group-btn">
      <span class="btn btn-small black-button btn-inverse" onclick="$(this).parent().find('input[type=file]').click();">Browse</span>
      <%= f.file_field :attachment, onchange: "$(this).parent().parent().find('.form-control').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
    </span>
    <span class="form-control"></span>
  </div>
  <%=f.fields_for :location do |location|%>
  <div>
    <%=location.label :expiration %>(Optional)
    <%=location.datetime_local_field :expiration%>
    <%=location.hidden_field (:long) %>
    <%=location.hidden_field (:lat) %>
    <%=location.hidden_field (:radius) %>
  </div>
  <%end%>
  <%= f.submit "DROP", class:"btn black-button" %>
<% end %>

app/views/songs/_show.html.erb
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title">Title: <%= song.name %></h3>
      </div>
      <div class="modal-body">
        <img src="<%= song.artwork %>" /><br>
        <audio controls>
          <source src="<%= song.attachment %>" type="audio/mpeg">
        </audio><br>
        <p>Artist: <%= song.artist.name %></p>
        <p>Expiration: <%= song.expire.strftime("%b %d, %Y") %><div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="70"
  aria-valuemin="0" aria-valuemax="100" style="width:70%">
    <span class="sr-only">70% Complete</span>
  </div>
</div></p>
        <p>Listens: <%= song.listens.count %></p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/songs/new.html.erb
<%= form_for :song, url: artist_songs_path(@artist) do |f| %>
  <div class="field">
    <%= f.label "Song Name" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Artwork" %>
    <%= f.file_field :artwork %>
  </div>
  <div class="field">
    <%= f.label "Song File" %>
    <%= f.file_field :attachment%>
  </div>
  <%=f.fields_for :location do |location|%>
  <div>
    <%=location.label :expiration %>(Optional)
    <%=location.datetime_local_field :expiration%>
    <%=location.hidden_field (:long) %>
    <%=location.hidden_field (:lat) %>
    <%=location.hidden_field (:radius) %>
  </div>
  <%end%>
  <%= f.submit "DROP" %>
<% end %>

app/views/songs/show.html.erb
<h1>Manage Song</h1>
<%= form_for [@song.artist, @song] do |f|%>
<%= f.text_field :name %>
<%= f.text_field :artwork %>
<%= f.submit %>
<% end %>

<%= button_to "DELETE SONG", artist_song_path(@song.artist, @song), method: :delete %>


<!-- <div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="<%= ((@song.expire.to_time.to_f - @song.created_at.to_time.to_f)/@song.created_at.to_time.to_f).round %>" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em;">

</div> -->