config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index]

  resources :artists do
    resources :songs
  end
  resources :mobile
  resources :favorites

  resources :session, except: [:destroy]
  resources :comments

  delete '/session/logout' => 'session#destroy'
  get '/songs/drop_song' => 'songs#drop_song'
  post '/songs/available' => 'songs#available_songs'

  resources :requests
  get '/nearby/requests' => 'requests#near'
  get '/near/requests/:params' => 'requests#near_songs'
  get '/songs/heat_map/:id' => 'songs#heat_map'

  root 'landings#index'
end

app/views/layouts/_dynamic_nav_link.html.erb
<% if request.env['PATH_INFO'].include?("users")%>
  <% if @user.artists.count == 0%>
    <%= link_to "Create Artist", new_artist_path, class: "nav-link "%>
  <% else %>
      <%= link_to "Manage Artist", artist_path(current_user.artists.first.id), class: "nav-link "%>
  <% end %>
<% else %>
  <%= link_to "User Home", user_path(current_user), class: "nav-link"%>
<% end %>

app/views/layouts/_media_player.html.erb
<section id="media-player" class="navmenu-fixed-left offcanvas">
  <div class="media-left">
  <h2>Available Songs</h2>
  <ul class="nav nav-pills">
    <li><a data-toggle="pill" href="#all_songs">All</a></li>
    <li><a data-toggle="pill" href="#favorite_songs">Favorites</a></li>
  </ul>

  <div class="tab-content">
    <div id="all_songs" class="tab-pane fade">
      <!-- <p>render songlist of all songs here</p> -->


    </div>
    <div id="favorite_songs" class="tab-pane fade">
      <%= render '/media/favorite_songs' %>
    </div>
  </div>
</div>
</section>
<div>
  <button type="button" class="" data-toggle="offcanvas" data-target="#media-player" data-canvas="body">
    <span class="icon-bar">SONGS</span>
  </button>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-inverse navbar-static-top">
  

    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <p class="navbar-brand logo" style="font-size:35px;"><span>EarShot</span></p>
      </div>
      <div class="collapse navbar-collapse" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item" style="font-size:20px;"><%= render 'layouts/dynamic_nav_link'%></li>
          <li class="nav-item" style="font-size:20px;"><%= link_to "Logout", session_logout_path, method: "delete", class: "nav-link"%></li>
        </ul>
      </div>
    </div>
  </div>  <!--end nav bar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Earshot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>




  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css"
    rel="stylesheet" type="text/css">
    <link href="https://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css"
    rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Orbitron|Righteous|Gloria+Hallelujah|Covered+By+Your+Grace|Permanent+Marker|Rock+Salt' rel='stylesheet' type='text/css'>
</head>
<body>
  <% if logged_in? %>
    <%=render partial: '/layouts/navbar' %>
  <% end %> <!-- end logged_in? conditional -->
  <%= yield %>

</body>
</html>